### PR TITLE
New Convnet for IBD pairs

### PR DESCRIPTION
**Pull request by samkohn**
I added a new convnet (ibd_ae.py) that processes a pair of events with both charge and time information encoded in the channels. The big changes were:
1. allow the number of channels at the end of the deconvolution to be different from 1
2. preprocess the input so that each feature (pixel in a given channel) is distributed with 0 mean and unit variance across all the images in the training set.

### CODE REVIEW

**Comment by eracah** [comment]
Good work! Is there a file that tests the Lasagne Network?

**Comment by samkohn** [comment]
I actually didn't mean to include those commits in the pull request. Anyways, yes I updated the ibd_ae.py to run off the new network. It's in my repository, https://github.com/samkohn/dayabay-learn. Right now it only runs for one epoch, but it otherwise plugs into the same methods used in the old convnet.

**Comment by samkohn** [comment]
The new convnet is having some training issues. The cost stays relatively constant over multiple epochs. I'm trying to hunt down the cause of this problem.

**Comment by samkohn** [comment]
OK, so it was due to how I initialized the weights (too large). Fixed now on my repo.

**Pull request merged**
